### ISSUE TITLE
初次使用未登入會顯示登入成功，但後面都正常。

### ISSUE THREAD

**Issue by leo424y** [fruitcake0525/ror_taichung#13]
第一次開啟時頁面跳訊息："Welcome! You have signed up successfully."

**Comment by koei1025** [comment]
@leo424y 你的操作步驟是什麼，因為我把db reset後重新註冊登入，顯示的訊息也都正常

**Comment by leo424y** [comment]
@koei1025 我的操作跟你一樣，可能是我自己本機cach的問題，先close好了，歹勢~~
