### ISSUE TITLE
Event 日期選擇 bug

### ISSUE THREAD

**Issue by leo424y** [fruitcake0525/ror_taichung#6]
每個月都有31天! XD

**Comment by leo424y** [comment]
不過送出後會自動修正，好神奇

**Comment by fruitcake0525** [comment]
已修正datatime-picker樣式，搭配Simple Form

參考資料:
https://github.com/plataformatec/simple_form/wiki/Custom-inputs-examples
https://github.com/smalot/bootstrap-datetimepicker

**Comment by leo424y** [comment]
https://quip.com/8h4DAzk1bR3a 前端測使用者事件變化可用  jquery
